# Generated by Django 5.0.6 on 2024-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_added_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=50)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='customer/')),
            ],
        ),
    ]
