# Generated by Django 5.0.6 on 2024-09-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_email', models.EmailField(max_length=50)),
                ('supplier_address', models.CharField(max_length=100)),
                ('supplier_phone', models.IntegerField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='supplier/')),
            ],
        ),
    ]
