# Generated by Django 5.0.6 on 2024-09-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
            preserve_default=False,
        ),
    ]
