# Generated by Django 5.1 on 2024-10-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
