# Generated by Django 5.1 on 2024-11-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
