# Generated by Django 5.1 on 2024-11-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_temporarycart_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalcart',
            options={'ordering': ['-date_added']},
        ),
    ]
