# Generated by Django 5.1 on 2024-11-01 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_finalcart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalcart',
            options={},
        ),
        migrations.AddField(
            model_name='finalcart',
            name='transfer_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
